#!/bin/sh
### BEGIN INIT INFO
# Provides:          scull-init
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Load scull module
### END INIT INFO

case "$1" in
    start)
        echo "Loading scull module"
        modprobe scull || insmod /lib/modules/$(uname -r)/scull.ko
        ;;
    stop)
        echo "Unloading scull module"
        rmmod scull || true
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit 0
